// Registers the Workbox service worker generated by scripts/generate-sw.mjs.
//
// Behaviour mirrors the old vite-plugin-pwa `registerType: 'autoUpdate'`: a new
// SW installs and activates silently (skipWaiting + clientsClaim in the SW),
// then the page reloads once onto the fresh assets.
//
// The reliable "a new version took over" signal is `controllerchange`, not the
// narrower `updatefound -> statechange` path: with clientsClaim the new SW can
// take control via routes that never emit updatefound on the current page (e.g.
// it finished installing on a previous load). We listen for controllerchange
// and reload exactly once. The listener is only armed when the page is ALREADY
// controlled at load time, so a first-ever install (no prior controller) claims
// the page silently without a spurious reload.
import { IS_NATIVE_BUILD } from '../native/platform';

export function registerSW(): void {
  // The native App is offline via its on-device bundle; a service worker inside
  // the WebView would fight Capacitor's asset cache and cause stale-version bugs
  // (docs/adr/0002). Never register it there.
  if (IS_NATIVE_BUILD) return;
  if (typeof window === 'undefined') return;
  if (!('serviceWorker' in navigator)) return;
  // /sw.js only exists in production builds (emitted post-build, not in dev).
  if (!import.meta.env.PROD) return;

  if (navigator.serviceWorker.controller) {
    let reloaded = false;
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      if (reloaded) return;
      reloaded = true;
      window.location.reload();
    });
  }

  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js')
      .then((registration) => {
        // Check immediately on load and hourly thereafter so both fresh visits
        // and long-lived tabs pick up a new deploy promptly.
        registration.update().catch(() => {});
        setInterval(() => void registration.update().catch(() => {}), 60 * 60 * 1000);
      })
      .catch(() => {
        /* registration failures are non-fatal; the app still works online */
      });
  });
}
