import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("wheel", "routes/wheel.tsx"),
  route("scene", "routes/scene.tsx"),
  route("warmup", "routes/warmup.tsx"),
  // Content Entry pages: one indexable page per warmup game (SEO surface).
  route("warmups/:slug", "routes/warmup-entry.tsx"),
  route("facts", "routes/facts.tsx"),
  route("more", "routes/more.tsx"),
  route("timer", "routes/timer.tsx"),
  route("character", "routes/character.tsx"),
  route("prompts", "routes/prompts.tsx"),
  route("suggestions", "routes/suggestions.tsx"),
  route("formats", "routes/formats.tsx"),
  route("reflection", "routes/reflection.tsx"),
  route("soundscape", "routes/soundscape.tsx"),
  route("status", "routes/status.tsx"),
  route("spine", "routes/spine.tsx"),
  route("jam", "routes/jam.tsx"),
  route("principles", "routes/principles.tsx"),
  route("monologue", "routes/monologue.tsx"),
  route("genres", "routes/genres.tsx"),
  route("harold", "routes/harold.tsx"),
  route("emotion", "routes/emotion.tsx"),
  route("constraints", "routes/constraints.tsx"),
  route("metronome", "routes/metronome.tsx"),
  route("variants", "routes/variants.tsx"),
  route("replay", "routes/replay.tsx"),
  route("deconstruction", "routes/deconstruction.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("privacy-policy", "routes/privacy-policy.tsx"),
  route("contact", "routes/contact.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
